### ISSUE TITLE
The evaluation of sentiment

### ISSUE THREAD

**Issue by GeneZC** [teapot123/JASen#3]
Accordig to my understanding, the evaluation of sentiment prediction is conducted at sentence-level instead of aspect-level, right?

**Comment by teapot123** [comment]
Thanks for your question! For each sentence, we output a tuple of <aspect, sentiment> so both the aspect and sentiment of the sentence are captured. Our current method can only output one tuple for each sentence. Do you mean you want to capture the sentiment for each aspect in a sentence?

**Comment by GeneZC** [comment]
Yes, exactly.

**Comment by teapot123** [comment]
Currently, our method is doing single-class classification for each sentence thus can only output one tuple for each sentence. Extracting sentiment at an aspect level can be a future work, such as extending it into a multi-class classification problem. Then a possible solution can be changing the single-class classification objective into a multi-class objective one in the CNN training objective.

**Comment by GeneZC** [comment]
Thanks a lot!
